---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy nginx configuration
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf_dir }}"
  notify: restart nginx

- name: Create empty nginx web directory
  file:
    path: "/usr/local/nginx/{{ server_name }}/html/"
    state: "{{ item }}"
  with_items:
    - absent
    - director
