---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy nginx configuration for ecommerce
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf_dir }}"
  notify: restart nginx

- name: Create empty nginx web directory
  file:
    path: "{{ nginx_web_dir }}"
    state: "{{ item }}"
  with_items:
    - absent
    - directory

- name: Place prod UI
  unarchive:
    src: html.zip
    dest: "{{ nginx_web_dir }}"
    mode: 0755
  notify: restart nginx
