---

- name: Set timezone to America/Chicago
  timezone:
    name: America/Los_Angeles

- name: Reload ansible_facts
  setup:

- name: Install management packages
  yum:
    name:
      - sysstat
      - iptraf
      - tcpdump
      - jq
      - libselinux-python
    state: present

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Install epel management packages
  yum:
    name:
      - iftop
    state: present
    enablerepo: epel

- name: Set ulimit on startup
  lineinfile:
    dest: /etc/security/limits.d/90-nproc.conf
    regexp: '\*.*nproc'
    line: "*\t-\tnproc\t8192"
    create: yes
  when:
    - common_limit_nproc is defined
    - common_limit_nproc | trim != ''
    - common_limit_nproc | int > 0

- name: Set ulimit on startup
  lineinfile:
    dest: /etc/security/limits.d/91-nofile.conf
    regexp: '\*.*nofile'
    line: "*\t-\tnofile\t8192"
    create: yes
  when:
    - common_limit_nofile is defined
    - common_limit_nofile | trim != ''
    - common_limit_nofile | int > 0
