---

- name: Import Nodesource RPM key
  shell: "curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash"

- name: Import Yarn RPM key
  shell: "curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo"

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs"
    state: present
    enablerepo: nodesource

- name: Ensure yarn is installed
  yum:
    name: "yarn"
    state: present

- name: Update NPM
  shell: "npm install -g npm@latest"
