---

- name: Set timezone to US/Pacific
  timezone:
    name: US/Pacific
  become: yes

- name: Reload ansible_facts
  setup:
  become: yes

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  become: yes

- name: Install required packages
  yum:
    name:
      - amazon-linux-extras
    state: present
  become: yes

- command:
    cmd: amazon-linux-extras enable python3.8
  become: yes

- name: Install required packages
  yum:
    name:
      - python3.8
      - nano
      - epel-release
      - yum-utils
    state: present
  become: yes

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3.8
  become: no

- name: Install python packges
  pip:
    name: "{{ item }}"
    executable: pip3.8
  loop:
    - tinydb
    - stripe
    - flask
  become: no

- name: Update all packages
  yum:
    name: "*"
    state: latest
  become: yes
